- block:
  - name: Configure tunnels
    ansible.builtin.template: 
      dest: /etc/network/interfaces.d/tunnels.cfg
      src: tunnels.j2
      owner: root
      mode: 0644

  - name: Enabling interfaces
    ansible.builtin.command: /sbin/ifup {{ item.name }}
    with_items: '{{tunnels}}'
    register: ifup_result
    changed_when: "'already configured' in ifup_result.stdout"
  when: tunnels is defined
