---
galaxy_info:
  author: Daniel Czerwonk
  description: Prometheus SNMP-Exporter 
  license: BSD 
  min_ansible_version: 1.2
  platforms:
    - name: Debian
      versions:
        - jessie
        - lenny
        - squeeze
        - wheezy
  categories:
    - networking
