- name: Ensure data dir exists
  ansible.builtin.file:
    name: /var/grafana
    state: directory
    owner: 472
    mode: "0750"

- name: Ensure docker container is running
  community.general.docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    pull: true
    volumes:
      - "/var/grafana:/var/lib/grafana"
    ports:
      - "127.0.0.1:3000:3000"
    env:
      GF_SERVER_ROOT_URL: "{{ grafana.fqdn }}"
    restart_policy: always
