- name: Ensure bird_exporter is installed
  unarchive:
    src: https://github.com/czerwonk/bird_exporter/releases/download/{{ bird_exporter_version }}/bird_exporter_{{ bird_exporter_version }}_linux_amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
  notify: Restart bird_exporter

- name: Ensure service is installed
  copy:
    src: bird_exporter.service
    dest: /usr/lib/systemd/system/bird_exporter.service
    mode: 0644
    owner: root
  register: systemd_unit

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: systemd_unit.changed

- name: Ensure service is running
  systemd:
    name: bird_exporter
    enabled: yes
    state: started