---

- name: Ensure bird exporter is installed 
  environment:
    GOPATH: /usr/local
  shell: /usr/local/go/bin/go get github.com/czerwonk/bird_exporter
  notify: Restart bird_exporter
  
- name: Ensure service is installed
  copy: src=bird_exporter.service dest=/lib/systemd/system/bird_exporter.service owner=root mode=0644
  notify: Reload systemd

- name: Ensure service is enabled
  service: name=bird_exporter enabled=yes

- name: Ensure service is started
  service: name=bird_exporter state=started
