- hosts: map
  roles:
    - ffe.packages
    - ffe.sysctl
    - ffe.tunnels
    - ffe.routing
    - ffe.iptables
    - { role: ffe.batman, when: mesh_enabled }
    - { role: ffe.fastd, when: mesh_enabled }
    - ffe.node_exporter
    - ffe.bird_exporter
