---
- hosts: supernodes
  roles:
    - ffe.packages
    - ffe.users
    - ffe.sysctl
    - ffe.tunnels
    - ffe.routing
    - ffe.iptables
    - ffe.openvpn
    - { role: ffe.unbound, when: mesh_enabled }
    - { role: ffe.ntpd, when: mesh_enabled }
    - { role: ffe.batman, when: mesh_enabled }
    - { role: ffe.dhcpd, when: mesh_enabled }
    - { role: ffe.fastd, when: mesh_enabled }
    - ffe.node-exporter
    - ffe.bird_exporter
    - { role: ffe.unbound_exporter, when: mesh_enabled }
