global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - /etc/prometheus/alerts.rules

scrape_configs:
  - job_name: 'snmp_ffe'
    scrape_interval: 60s
    scrape_timeout: 30s
    target_groups:
      - targets: [
                  'gw01.e-alten.dev.freifunk-essen.net',
                  'gw01.e-awo-jlh.dev.freifunk-essen.net', 
                  'gw01.e-esh.dev.freifunk-essen.net', 
                  'gw01.e-hatzp.dev.freifunk-essen.net',
                  'gw01.e-mauve.dev.freifunk-essen.net',
                  'gw01.e-volks.dev.freifunk-essen.net',
                  'gw01.e-zollv.dev.freifunk-essen.net',
                  'gw01.e-erbsl.dev.freifunk-essen.net',
                  'gw01.e-boegel.dev.freifunk-essen.net',
                  'gw01.e-heidb.dev.freifunk-essen.net',
                  'gw01.e-hambu.dev.freifunk-essen.net'
                 ]
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)(:80)?
        target_label: __param_address
        replacement: ${1}
      - source_labels: [__param_address]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: 127.0.0.1:9116

  - job_name: 'snmp_ffrl'
    scrape_interval: 60s
    scrape_timeout: 30s
    target_groups:
      - targets: ['gw01.fah.dev.freifunk-essen.net',
                  'gw01.stk-d.dev.freifunk-essen.net',
                  'gw01.lanuv-e.dev.freifunk-essen.net']
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)(:80)?
        target_label: __param_address
        replacement: ${1}
      - source_labels: [__param_address]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: 127.0.0.1:9116

  - job_name: 'node'
    scrape_interval: 20s
    target_groups:
      - targets: ['sn-a.ak.ber.ffe.rocks:9100',
                  'sn-b.ak.ber.ffe.rocks:9100',
                  'sn-a.ov.lil.ffe.rocks:9100',
                  'sn-b.ov.lil.ffe.rocks:9100',
                  'map.ffe.rocks:9100',
                  'vpn.ffe.rocks:9100']

  - job_name: 'unifi'
    scrape_interval: 30s
    target_groups:
      - targets: ['localhost:9120']
