---

groups:
- name: recording
  rules:
    - record: node_bb:ingress:rate1m_by_peer
      expr: irate(node_network_receive_bytes{job="node_bb",site="ix.dus",device="eth0.43"}[1m]) * 8
      labels:
        peer: FFRL
        kind: peer
        site: dus
    - record: node_bb:egress:rate1m_by_peer
      expr: irate(node_network_transmit_bytes{job="node_bb",site="ix.dus",device="eth0.43"}[1m]) * 8
      labels:
        peer: FFRL
        kind: peer
        site: dus

    - record: node_bb:ingress:rate1m_by_peer
      expr: irate(node_network_receive_bytes{job="node_bb",site="ix.dus",device="eth1.10"}[1m]) * 8
      labels:
        peer: DECIX-DUS
        kind: ixp
        site: dus
    - record: node_bb:egress:rate1m_by_peer
      expr: irate(node_network_transmit_bytes{job="node_bb",site="ix.dus",device="eth1.10"}[1m]) * 8
      labels:
        peer: DECIX-DUS
        kind: ixp
        site: dus

    - record: node_bb:ingress:rate1m_by_peer
      expr: irate(node_network_receive_bytes{job="node_bb",site="ix.dus",device="eth1.11"}[1m]) * 8
      labels:
        peer: DECIX-FRA
        kind: ixp
        site: dus
    - record: node_bb:egress:rate1m_by_peer
      expr: irate(node_network_transmit_bytes{job="node_bb",site="ix.dus",device="eth1.11"}[1m]) * 8
      labels:
        peer: DECIX-FRA
        kind: ixp
        site: dus

    - record: node_bb:ingress:rate1m_by_peer
      expr: irate(node_network_receive_bytes{job="node_bb",site="ix.dus",device="eth1.83"}[1m]) * 8
      labels:
        peer: LWLCOM
        kind: transit
        site: dus
    - record: node_bb:egress:rate1m_by_peer
      expr: irate(node_network_transmit_bytes{job="node_bb",site="ix.dus",device="eth1.83"}[1m]) * 8
      labels:
        peer: LWLCOM
        kind: transit
        site: dus

    - record: node_bb:ingress:rate1m_by_peer
      expr: irate(node_network_receive_bytes{job="node_bb",site="ix.dus",device="eth1.46"}[1m]) * 8
      labels:
        peer: routing-rocks
        kind: peer
        site: dus
    - record: node_bb:egress:rate1m_by_peer
      expr: irate(node_network_transmit_bytes{job="node_bb",site="ix.dus",device="eth1.46"}[1m]) * 8
      labels:
        peer: routing-rocks
        kind: peer
        site: dus

    - record: node_bb:ingress:rate1m_by_peer
      expr: irate(node_network_receive_bytes{job="node_bb",site="ix.dus",device=~"eth1.7[01]"}[1m]) * 8
      labels:
        peer: philuweb
        kind: transit
        site: dus
    - record: node_bb:egress:rate1m_by_peer
      expr: irate(node_network_transmit_bytes{job="node_bb",site="ix.dus",device=~"eth1.7[01]"}[1m]) * 8
      labels:
        peer: philuweb
        kind: transit
        site: dus
    
    - record: node_bb:ingress:rate1m_by_peer
      expr: irate(node_network_receive_bytes{job="node_bb",site="ix.dus",device="eth1.2107"}[1m]) * 8
      labels:
        peer: COMMUNITY-IX
        kind: ixp
        site: dus
    - record: node_bb:egress:rate1m_by_peer
      expr: irate(node_network_transmit_bytes{job="node_bb",site="ix.dus",device="eth1.2107"}[1m]) * 8
      labels:
        peer: COMMUNITY-IX
        kind: ixp
        site: dus

    - record: node_bb:ingress:rate1m_by_peer
      expr: irate(node_network_receive_bytes{job="node_bb",site="ix.dus",device=~"gre-sn."}[1m]) * 8
      labels:
        peer: FF-E Supernodes
        kind: downstream
        site: dus
    - record: node_bb:egress:rate1m_by_peer
      expr: irate(node_network_transmit_bytes{job="node_bb",site="ix.dus",device=~"gre-sn."}[1m]) * 8
      labels:
        peer: FF-E Supernodes
        kind: downstream
        site: dus

    - record: node_bb:ingress:rate1m_by_peer
      expr: irate(node_network_receive_bytes{job="node_bb",site="ix.dus",device="eth1.42"}[1m]) * 8
      labels:
        peer: FF-E City-Backbone
        kind: downstream
        site: dus
    - record: node_bb:egress:rate1m_by_peer
      expr: irate(node_network_transmit_bytes{job="node_bb",site="ix.dus",device="eth1.42"}[1m]) * 8
      labels:
        peer: FF-E City-Backbone
        kind: downstream
        site: dus

    - record: node_bb:ingress:outside_sum_rate1m
      expr: sum(node_bb:ingress:rate1m_by_peer{kind!="downstream"})
      labels:
        site: dus

    - record: node_bb:egress:outside_sum_rate1m
      expr: sum(node_bb:egress:rate1m_by_peer{kind!="downstream"})
      labels:
        site: dus
