- name: Ensure packages are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - tmux 
    - zsh
    - git
    - mc
    - htop
    - iftop
    - ifstat
    - fail2ban
    - dnsutils
    - tcpdump
    - logrotate
    - apt-transport-https
    - ca-certificates
    - conntrack
