- name: "Ensure output directory for site exists: {{ site.name }}"
  ansible.builtin.file:
    path: "{{ site_config_dir }}/{{ site.name }}"
    state: directory
    mode: "0755"

- name: "Ensure boot.config for site is up to date: {{ site.name }}"
  ansible.builtin.template:
    src: config.boot.bb.j2
    dest: "{{ site_config_dir }}/{{ site.name }}/config.boot"
    mode: "0644"
