- name: Ensure unbound is installed
  ansible.builtin.apt:
    name: unbound
    state: present
    update_cache: true

- name: Ensure unbound config dir exists
  ansible.builtin.file:
    name: "{{ unbound_config_dir }}"
    state: directory
    owner: root
    mode: "0500"

- name: Configure unbound
  ansible.builtin.template:
    src: supernode.conf.j2
    dest: "{{ unbound_config_dir }}/unbound.conf.d/supernode.conf"
    owner: root
    mode: "0644"
  notify: Restart unbound
