- name: Ensure newest caddy version is installed
  ansible.builtin.unarchive:
    src: https://github.com/caddyserver/caddy/releases/download/v{{ caddy_version }}/caddy_{{ caddy_version }}_linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: true
  tags:
    - upgrade
  notify: Restart caddy

- name: Ensure caddy config directory exists
  ansible.builtin.file:
    path: /etc/caddy
    owner: www-data
    mode: "0750"
    state: directory

- name: Ensure caddy directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: www-data
    mode: "0750"
    state: directory
  with_items:
    - "/etc/caddy"
    - "/var/www/.local/"
    - "/var/www/.config/"
    - "/var/log/caddy"

- name: Ensure config is up to date
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: www-data
    mode: "0640"
  notify: Restart caddy

- name: Ensure service unit exists
  ansible.builtin.copy:
    src: caddy.service
    dest: /lib/systemd/system/caddy.service
    mode: "0400"
    owner: root
  register: systemd

- name: Ensure service is enabled and started
  ansible.builtin.systemd:
    daemon_reload: true
    name: caddy
    state: started
    enabled: true
  when: systemd.changed
