- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name: prometheus-snmp-exporter

- name: Configure snmp_exporter
  ansible.builtin.copy:
    src: snmp.yml
    dest: /etc/prometheus/snmp.yml
    owner: root
    mode: "0644"

- name: Start service
  ansible.builtin.service:
    name: prometheus-snmp-exporter
    state: restarted
    enabled: true
