- name: Ensure dependencies are installed
  apt: 
    name: prometheus-snmp-exporter

- name: Configure snmp_exporter
  copy: 
    src: snmp.yml 
    dest: /etc/prometheus/snmp.yml 
    owner: root 
    mode: 0644

- name: Start service
  service: 
    name: prometheus-snmp-exporter 
    state: restarted
    enabled: yes
