- name: Reload bird
  ansible.builtin.command: birdc configure soft

- name: Reload bird6
  ansible.builtin.command: birdc6 configure soft

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
