---

- name: Ensure package is not installed
  apt: name=golang state=absent

- name: Check for installed go version
  command: /usr/local/go/bin/go version
  ignore_errors: yes
  register: go_version_installed
  changed_when: false

- block:
  - name: Remove old go version
    file: path=/usr/local/go state=absent

  - name: Download the Go tarball
    get_url: url=https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz
             dest=/tmp

  - name: Extract new version
    unarchive: src=/tmp/go{{ go_version }}.linux-amd64.tar.gz
               dest=/usr/local/
               copy=no

  - name: Ensure GOROOT is in path
    copy: src=go_profile dest=/etc/profile.d/go.sh owner=root mode=0644

  when: go_version_installed|failed or not '"{{ go_version }}" in go_version_installed.stdout'
