---
- name: Ensure packages are installed
  apt: 
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - tmux 
    - zsh
    - git
    - mc
    - htop
    - iftop
    - ifstat
    - fail2ban
    - dnsutils
    - tcpdump
    - logrotate
    - apt-transport-https 
    - ca-certificates
    - conntrack
