---
- name: Ensure packages are installed
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - tmux 
    - zsh
    - git
    - mc
    - htop
    - iftop
    - ifstat
    - fail2ban
    - dnsutils
    - tcpdump
    - logrotate
    - apt-transport-https 
    - ca-certificates
    - conntrack

- name: Ensure go is installed
  include: install_go.yml
