---

- name: Ensure newest caddy version is installed
  unarchive:
    src: https://github.com/caddyserver/caddy/releases/download/v2.4.6/caddy_2.4.6_linux_amd64.tar.gz 
    dest: /usr/local/bin
    remote_src: yes
  tags:
    - upgrade
  notify: Restart caddy

- name: Ensure caddy config directory exists
  file:
    path: /etc/caddy
    owner: www-data
    mode: 0755
    state: directory

- name: Ensure caddy directories exists
  file:
    path: "{{ item }}"
    owner: www-data
    mode: 0755
    state: directory
  with_items:
  - "/etc/caddy"
  - "/var/www/.local/"
  - "/var/www/.config/"
  - "/var/log/caddy"

- name: Ensure config is up to date
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    mode: 0644
  notify: Restart caddy

- name: Ensure service unit exists
  copy:
    src: caddy.service
    dest: /lib/systemd/system/caddy.service
    mode: 0644
    owner: root
  register: systemd

- name: Ensure service is enabled and started
  systemd:
    daemon_reload: yes
    name: caddy
    state: started
    enabled: yes
  when: systemd.changed
