---
- name: Ensure radvd is installed
  apt: name=radvd state=present update_cache=yes

- name: Configure radvd
  template: src=radvd.conf.j2 dest=/etc/radvd.conf owner=root mode=0400
  notify: Restart radvd

- name: Configure rsyslogd
  copy: src=radvd.rsyslog.conf dest=/etc/rsyslog.d/radvd.conf owner=root mode=0644
  notify: Restart rsyslogd
