- name: Ensure wireguard is installed
  apt:
    name: 
    - wireguard
    - wireguard-dkms 

- name: Configure wg0
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: 0644
    owner: root
  notify:
  - Reload wg0

- name: Ensure service is enabled
  systemd:
    name: wg-quick@wg0
    enabled: yes

- name: Ensure service is running
  systemd:
    name: wg-quick@wg0
    state: started
