---
- name: Update docker list
  copy: src=docker.list.{{ansible_distribution_release}} dest=/etc/apt/sources.list.d/docker.list owner=root mode=0644

- name: Ensure docker is installed
  apt: name=docker-engine update_cache=yes state=installed
