- name: Ensure fastd is installed
  ansible.builtin.apt:
    name: fastd
    state: present

- name: Ensure user exists
  ansible.builtin.user:
    name: fastd
    system: true

- name: Ensure fastd config dir exists
  ansible.builtin.file:
    name: "{{ fastd_config_dir }}"
    state: directory
    owner: fastd
    mode: "0500"

- name: Ensure fastd config subdirs exists
  ansible.builtin.file:
    name: "{{ fastd_config_dir }}/{{ item }}"
    state: directory
    owner: fastd
    mode: "0500"
  with_items:
    - essen

- name: Create config files
  ansible.builtin.template:
    src: "fastd_{{ item }}.conf.j2"
    dest: "{{ fastd_config_dir }}/{{ item }}/fastd.conf"
    owner: fastd
    mode: "0400"
  with_items:
    - essen

- name: Ensure dummy dir exists
  ansible.builtin.file:
    name: "{{ fastd_config_dir }}/essen/dummy"
    state: directory
    owner: fastd
    mode: "0500"

- name: Copy blacklist.sh
  ansible.builtin.copy:
    src: blacklist.sh
    dest: "{{ fastd_config_dir }}/essen/blacklist.sh"
    owner: fastd
    mode: "0500"

- name: Copy blacklist
  ansible.builtin.copy:
    src: fastd-blacklist.json
    dest: "{{ fastd_config_dir }}/fastd-blacklist.json"
    owner: fastd
    mode: "0400"

- name: Configure rsyslog
  ansible.builtin.copy:
    src: fastd.rsyslog.conf
    dest: /etc/rsyslog.d/fastd.conf
    owner: root
    mode: "0644"
  notify: Restart rsyslog

- name: Ensure logrotate is configured
  ansible.builtin.copy:
    src: fastd_logrotate
    dest: /etc/logrotate.d/fastd
    mode: "0644"
    owner: root

- name: Ensure service is enabled
  ansible.builtin.systemd:
    name: fastd@essen
    enabled: true
    state: started
