---

- include_tasks: download.yml

- stat: path=/lib/init/upstart-job
  register: upstart
- stat: path=/bin/systemctl
  register: systemd

- include_tasks: configure_initd.yml
  when: upstart.stat.exists

- include_tasks: configure_systemd.yml
  when: systemd.stat.exists    
