---

- include: download.yml

- stat: path=/lib/init/upstart-job
  register: upstart
- stat: path=/bin/systemctl
  register: systemd

- include: configure_initd.yml
  when: upstart.stat.exists

- include: configure_systemd.yml
  when: systemd.stat.exists    
