- name: Ensure node_exporter is installed
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: true
  notify: Restart bird_exporter

- name: Ensure systemd is configured
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/node_exporter.service
    mode: "0400"
  register: systemd_unit

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: systemd_unit.changed

- name: Start node-exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: true
