---
galaxy_info:
  author: Daniel Czerwonk
  description: BGP peering setup
  license: BSD 
  min_ansible_version: 1.2
  platforms:
    - name: Debian
      versions:
        - jessie
        - lenny
        - squeeze
        - wheezy
  categories:
    - networking
dependencies: [ ffe.tunnels ]
