---

- name: Configure iptables 
  template: src=iptables.rules.j2 dest=/etc/iptables.rules owner=root mode=0600

- name: Reload iptables
  shell: iptables-restore /etc/iptables.rules

- name: Configure ip6tables
  template: src=ip6tables.rules.j2 dest=/etc/ip6tables.rules owner=root mode=0600

- name: Reload ip6tables
  shell: ip6tables-restore /etc/ip6tables.rules
