---

- name: Ensure unbound exporter is installed 
  environment:
    GOPATH: /usr/local
  shell: /usr/local/go/bin/go get github.com/kumina/unbound_exporter
  notify: Restart unbound_exporter
  
- name: Ensure service is installed
  copy: src=unbound_exporter.service dest=/lib/systemd/system/unbound_exporter.service owner=root mode=0644
  notify: Reload systemd

- name: Ensure service is enabled
  service: name=unbound_exporter enabled=yes

- name: Ensure service is started
  service: name=unbound_exporter state=started
