- name: Ensure bird_exporter is installed
  ansible.builtin.unarchive:
    src: https://github.com/czerwonk/bird_exporter/releases/download/{{ bird_exporter_version }}/bird_exporter_{{ bird_exporter_version }}_linux_amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: true
  notify: Restart bird_exporter

- name: Ensure service is installed
  ansible.builtin.copy:
    src: bird_exporter.service
    dest: /usr/lib/systemd/system/bird_exporter.service
    mode: "0400"
    owner: root
  register: systemd_unit

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: systemd_unit.changed

- name: Ensure service is running
  ansible.builtin.systemd:
    name: bird_exporter
    enabled: true
    state: started
