global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

rule_files:
  - /etc/prometheus/alerts.rules.yml
  - /etc/prometheus/recording.rules.yml

scrape_configs:
  - job_name: 'snmp'
    scrape_interval: 30s
    scrape_timeout: 30s
    file_sd_configs:
      - files: 
          - '/etc/prometheus/tgroups/snmp*.yml'
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.17.0.1:9116

  - job_name: 'node'
    scrape_interval: 20s
    file_sd_configs:
      - files:
        - '/etc/prometheus/tgroups/node*.yml'
    relabel_configs:
      - source_labels: [__address__]
        regex:  '(.*)\.(de\.)?(ff-e\.net):\d+'
        target_label: instance
        replacement: '${1}'

  - job_name: 'bird'
    scrape_interval: 30s
    file_sd_configs:
      - files:
        - '/etc/prometheus/tgroups/bird*.yml'
    relabel_configs:
      - source_labels: [__address__]
        regex:  '(.*)\.(de\.)?(ff-e\.net):\d+'
        target_label: instance
        replacement: '${1}'

  - job_name: 'unifi'
    scrape_interval: 30s
    static_configs:
      - targets: ['172.16.0.6:9120']

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
          - "172.17.0.1:9093"
