---

- name: Ensure output directory for site {{ site.name }} exists
  file: path={{ site_config_dir }}/{{ site.name }} state=directory mode=0755

- name: Ensure boot.config of site {{ site.name }} is up to date
  template: src=boot.config.j2 dest={{ site_config_dir }}/{{ site.name }}/boot.config mode=0644

- name: Ensure openvpn up script is up to date
  template: src=openvpn-up.sh.j2 dest={{ site_config_dir }}/{{ site.name }}/openvpn-up.sh mode=0755

- name: Ensure start scripts are up to date
  copy: src=scripts dest={{ site_config_dir }}/{{ site.name }}/scripts

- file: path={{ site_config_dir }}/{{ site.name }}/scripts/post-config.d state=directory mode=0750
- template: src=start_tunneldigger.sh.j2 dest={{ site_config_dir }}/{{ site.name }}/scripts/post-config.d/start_tunneldigger.sh mode=0755

- file: path={{ site_config_dir }}/{{ site.name }}/scripts/tunneldigger state=directory mode=0750
- template: src=tunneldigger-hook.sh.j2 dest={{ site_config_dir }}/{{ site.name }}/scripts/tunneldigger/hook.sh mode=0755
