---

- name: Ensure output directory for site {{ site.name }} exists
  file: path={{ site_config_dir }}/{{ site.name }} state=directory mode=0755

- name: Ensure boot.config of site {{ site.name }} is up to date
  template: src=config.boot.j2 dest={{ site_config_dir }}/{{ site.name }}/config.boot mode=0644

- name: Ensure script dirs exists
  file: path={{ site_config_dir }}/{{ site.name }}/{{ dir }} mode=0755 state=directory
  with_items:
    - "scripts"
    - "scripts/post-config.d"
  loop_control:
    loop_var: dir

- file: path={{ site_config_dir }}/{{ site.name }}/scripts/post-config.d state=directory mode=0750
- template: src=start_tunneldigger.sh.j2 dest={{ site_config_dir }}/{{ site.name }}/scripts/post-config.d/start_tunneldigger.sh mode=0755

- file: path={{ site_config_dir }}/{{ site.name }}/scripts/tunneldigger state=directory mode=0750
- template: src=tunneldigger-hook.sh.j2 dest={{ site_config_dir }}/{{ site.name }}/scripts/tunneldigger/hook.sh mode=0755
