---

- name: Ensure output directory for site {{ site.name }} exists
  file: path={{ site_config_dir }}/{{ site.name }} state=directory mode=0755

- name: Ensure boot.config of site {{ site.name }} is up to date
  template: src=config.boot.dsl.j2 dest={{ site_config_dir }}/{{ site.name }}/config.boot mode=0644

- name: Ensure script dirs exists
  file: path={{ site_config_dir }}/{{ site.name }}/{{ dir }} mode=0755 state=directory
  with_items:
    - "scripts"
    - "scripts/post-config.d"
  loop_control:
    loop_var: dir
