- name: Ensure batctl is installed
  ansible.builtin.apt:
    name: batctl
    state: present
    update_cache: true

- name: Configure mesh interface
  ansible.builtin.template:
    dest: /etc/network/interfaces.d/batman.cfg
    src: batman.j2
    owner: root
    mode: "0400"

# - name: Enabling interfaces
#   ansible.builtin.command: "/sbin/ifup {{ mesh.interface.name }}"
#   register: ifup_result
#   changed_when: "'already configured' in ifup_result.stdout"
