- name: Ensure mesh-announce is up to date
  ansible.builtin.git:
    repo: 'https://github.com/ffnord/mesh-announce'
    dest: /opt/mesh-announce

- name: Ensure respondd is configured
  ansible.builtin.template:
    src: respondd.conf.j2
    dest: /etc/respondd.conf
    mode: "0400"
    owner: root

- name: Ensure service is configured
  ansible.builtin.copy:
    src: respondd.service
    dest: /etc/systemd/system/respondd.service
    mode: "0400"
  register: service

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: service.changed

- name: Ensure service is enabled and started
  ansible.builtin.systemd:
    name: respondd
    enabled: true
    state: started
