- name: Ensure mesh-announce is up to date
  git:
    repo: 'https://github.com/ffnord/mesh-announce'
    dest: /opt/mesh-announce

- name: Ensure respondd is configured
  template:
    src: respondd.conf.j2
    dest: /etc/respondd.conf
    mode: 0400
    owner: root

- name: Ensure service is configured
  copy:
    src: respondd.service
    dest: /etc/systemd/system/respondd.service
  register: service

- name: Reload systemd
  systemd: 
    daemon_reload: yes
  when: service.changed

- name: Ensure service is enabled and started
  systemd: 
    name: respondd
    enabled: yes
    state: started
