---
- hosts: 
    - monitoring
  become: yes
  become_method: sudo
  roles:
    - { role: ffe.prometheus }
    - { role: ffe.alertmanager }
    - { role: ffe.snmp-exporter }
    - { role: ffe.node-exporter }
