---
- hosts: supernodes
  become: yes
  become_method: sudo
  roles:
    - ffe.packages
    - ffe.sysctl
    - ffe.tunnels
    - ffe.peerings
    - ffe.iptables
    - ffe.openvpn
    - { role: ffe.meshing, when: fastd_enabled }
