---
- hosts: supernodes
  become: yes
  become_method: sudo
  roles:
    - ffe.packages
    - ffe.sysctl
    - ffe.tunnels
    - ffe.peerings
    - ffe.iptables
    - ffe.openvpn
    - { role: ffe.batman, when: mesh_enabled }
    - { role: ffe.dhcpd, when: mesh_enabled }
    - { role: ffe.radvd, when: mesh_enabled }
    - { role: ffe.fastd, when: mesh_enabled }
