---
galaxy_info:
  author: Daniel Czerwonk
  description: Docker
  license: BSD
  min_ansible_version: 1.2
  platforms:
    - name: Debian
      versions:
        - jessie
        - wheezy
dependencies: [ ffe.packages ]
