- name: Ensure wireguard is installed
  ansible.builtin.apt:
    name: wireguard-tools

- name: Configure wg0
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: "0640"
    owner: root
  notify:
    - Reload wg0

- name: Ensure service is enabled
  ansible.builtin.systemd:
    name: wg-quick@wg0
    enabled: true

- name: Ensure service is running
  ansible.builtin.systemd:
    name: wg-quick@wg0
    state: started
