---
- name: Ensure openvpn is installed
  apt: name=openvpn state=present update_cache=yes

- name: Ensure openvpn config dir exists
  file: name={{openvpn_config_dir}} state=directory owner=root mode=0755

- name: Ensure keys dir exists
  file: name={{openvpn_config_dir}}/keys state=directory owner=root mode=0700

- name: Ensure ccd dir exists
  file: name={{openvpn_config_dir}}/ccd state=directory owner=root mode=0755

- name: Creating up script
  template: src=on_up.sh.j2 dest={{openvpn_config_dir}}/on_up.sh owner=root mode=0755

- name: Copy down script
  copy: src=on_down.sh dest={{openvpn_config_dir}}/on_down.sh owner=root mode=0755

- name: Creating ccd files
  template: src=ccd.j2 dest={{openvpn_config_dir}}/ccd/{{ item.vpn_name | default(item.name) }} owner=root mode=0444
  with_items: '{{dsl_sites}}'

- name: Configure openvpn server
  template: src=server.conf.j2 dest={{openvpn_config_dir}}/server.conf owner=root mode=0600
  notify: Restart openvpn

- name: Ensure logrotate config exists
  copy: src=openvpn_logrotate dest=/etc/logrotate.d/openvpn mode=0644 owner=root

- name: Ensure service is enabled
  systemd:
    name: openvpn@server
    enabled: yes
    state: started
